##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/mate-panel
    - aptitude
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - expect #required for unbuffer
    - gir1.2-freedesktop
    - git
    - gobject-introspection
    - gtk-doc-tools
    - libatk1.0-dev
    - libcairo2-dev
    - libdconf-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libgtk-layer-shell-dev
    - libice-dev
    - libmate-desktop-dev
    - libmate-menu-dev
    - libmateweather-dev
    - libpango1.0-dev
    - librsvg2-dev
    - libsm-dev
    - libsoup2.4-dev
    - libwnck-3-dev
    - libx11-dev
    - libxau-dev
    - libxrandr-dev
    - lsb-release
    - make
    - mate-common
    - meson
    - yelp-tools

before_scripts:
  - ./html-cppcheck
  - ./install-from-git https://github.com/mate-desktop/mate-common master

build_scripts:
  - ./before-build
  - ./make-scanbuild '--enable-compile-warnings=maximum'
  - ./after-build

after_scripts:
  - if [ -f "gen-index" ]; then ./gen-index -l 20 -i https://raw.githubusercontent.com/${OWNER_NAME}/${REPO_NAME}/master/icons/16x16/${REPO_NAME}.png; fi
