##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-cafe-team/cafe-panel
    - aptitude
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - expect #required for unbuffer
    - gir1.2-freedesktop
    - git
    - gobject-introspection
    - ctk-doc-tools
    - libatk1.0-dev
    - libcairo2-dev
    - libdconf-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libctk-3-dev
    - libctk-layer-shell-dev
    - libice-dev
    - libpango1.0-dev
    - librsvg2-dev
    - libsm-dev
    - libsoup2.4-dev
    - libwnck-3-dev
    - libx11-dev
    - libxau-dev
    - libxrandr-dev
    - lsb-release
    - make
    - meson
    - yelp-tools

    #required for cafe-desktop
    - intltool
    - iso-codes
    - libglib2.0-doc
    - libstartup-notification0-dev
    - libtool
    - libxml2-dev

before_scripts:
  - ./html-cppcheck
  - ./debrepo-install 'libctk-3-dev gir1.2-ctk-3.0 libctk-3-common libctk-3-0 libctk-3-doc'
  - ./install-from-git https://github.com/cafe-desktop/cafe-common master
  - ./install-from-git https://github.com/cafe-desktop/cafe-desktop master
  - ./install-from-git https://github.com/cafe-desktop/cafe-menus master
  - ./install-from-git https://github.com/cafe-desktop/libcafeweather master

build_scripts:
  - ./before-build
  - ./make-scanbuild '--enable-compile-warnings=maximum'
  - ./after-build

after_scripts:
  - if [ -f "gen-index" ]; then ./gen-index -l 20 -i https://raw.githubusercontent.com/${OWNER_NAME}/${REPO_NAME}/master/icons/16x16/${REPO_NAME}.png; fi
